services:
  # * ------------------------------
  # *   Books Database
  # * ------------------------------
  books-db:
    image: postgres:14.18
    container_name: books-db
    ports:
      - "${BOOKS_DATABASE_PORT}:5432"
    networks:
      - cmpc-net
    volumes:
      - pgdata_books:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${BOOKS_DATABASE_NAME}
      - POSTGRES_USER=${BOOKS_DATABASE_USER}
      - POSTGRES_PASSWORD=${BOOKS_DATABASE_PASSWORD}

  # * ------------------------------
  # *   Frontend
  # * ------------------------------
  books-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=${API_URL}
    container_name: books-app
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - cmpc-net
    environment:
      - NODE_ENV=production

  # * ------------------------------
  # *   API Books
  # * ------------------------------
  api-books:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: api-books
    ports:
      - "${API_BOOKS_PORT}:8080"
    networks:
      - cmpc-net
    volumes:
      - ./backend/src:/usr/src/app/src
    command: npm run start:prod
    environment:
      - DATABASE_HOST=books-db
      - DATABASE_PORT=${BOOKS_DATABASE_PORT}
      - DATABASE_NAME=${BOOKS_DATABASE_NAME}
      - DATABASE_USER=${BOOKS_DATABASE_USER}
      - DATABASE_PASSWORD=${BOOKS_DATABASE_PASSWORD}
      - PORT=${API_BOOKS_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - books-db

networks:
  cmpc-net:
    name: cmpc-net
    driver: bridge

volumes:
  pgdata_books:
