services:
  # * ------------------------------
  # *   Books Database
  # * ------------------------------
  books-db:
    image: postgres:14.18
    container_name: books-db
    ports:
      - "${BOOKS_DATABASE_PORT}:5432"
    networks:
      - cmpc-net
    volumes:
      - pgdata_books:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${BOOKS_DATABASE_NAME}
      - POSTGRES_USER=${BOOKS_DATABASE_USER}
      - POSTGRES_PASSWORD=${BOOKS_DATABASE_PASSWORD}

  # * ------------------------------
  # *   Frontend
  # * ------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3174"
    networks:
      - cmpc-net
    command: npm run start:prod
    environment:
      - PORT=${FRONTEND_PORT}

  # * ------------------------------
  # *   API Books
  # * ------------------------------
  api-books:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: api-books
    ports:
      - "${API_BOOKS_PORT}:8080"
    networks:
      - cmpc-net
    command: npm run start:prod
    environment:
      - PORT=${API_BOOKS_PORT}

networks:
  cmpc-net:
    name: cmpc-net
    driver: bridge

volumes:
  pgdata_books:
