services:
  # * ------------------------------
  # *   Books Database
  # * ------------------------------
  books-db:
    image: postgres:14.18
    container_name: books-db
    ports:
      - "${BOOKS_DATABASE_PORT}:5432"
    networks:
      - cmpc-net
    volumes:
      - pgdata_books:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${BOOKS_DATABASE_NAME}
      - POSTGRES_USER=${BOOKS_DATABASE_USER}
      - POSTGRES_PASSWORD=${BOOKS_DATABASE_PASSWORD}

  # * ------------------------------
  # *   Frontend
  # * ------------------------------
  books-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: books-app
    ports:
      - "${FRONTEND_PORT}:3174"
    networks:
      - cmpc-net
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /usr/src/app/src
          ignore:
            - node_modules
    environment:
      - PORT=${FRONTEND_PORT}

  # * ------------------------------
  # *   API Books
  # * ------------------------------
  api-books:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-books
    ports:
      - "${API_BOOKS_PORT}:8080"
    networks:
      - cmpc-net
    volumes:
      - ./backend/src:/usr/src/app/src
    command: npm run start:dev
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /usr/src/app/src
          ignore:
            - node_modules
    environment:
      - DATABASE_HOST=books-db
      - DATABASE_PORT=${BOOKS_DATABASE_PORT}
      - PORT=${API_BOOKS_PORT}
    depends_on:
      - books-db

networks:
  cmpc-net:
    name: cmpc-net
    driver: bridge

volumes:
  pgdata_books:
